Issue Solved. Eclipse java.lang.NoClassDefFoundError: org.w3c.dom.ElementTraversal. To avoid this error, you simply add xml-apis to your pom.xml. The version must be 1.4.01, because with 2.0.2 this issue is not solved due to xerces problem.